#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the dayOfProgrammer function below.
def dayOfProgrammer(year):
    if(year>=1700 and year<1918):
        leap=False
        if(year%4==0):
            leap=True
       
    if(year>1918 and year<=2700):
        leap=False
        if(year%400==0):
            leap=True
        elif(year%4==0 and year%100!=0):
            leap=True

    if(year>=1700 and year<=2700 and year!=1918 and leap==False):
        return "13.09."+str(year)
    elif(year>=1700 and year<=2700 and year!=1918 and leap==True):
        return "12.09."+str(year)
    elif(year==1918):
        return "26.09.1918"
 



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    year = int(input().strip())

    result = dayOfProgrammer(year)

    fptr.write(result + '\n')

    fptr.close()
