#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the repeatedString function below.
def repeatedString(s, n):
    count=0
    a=''
    q=len(s)
    sa=s*n
    for i in range(0,len(sa),q):
        x=i
        if (i+q)<=n:
            y=i+q
            a=a+sa[x:y]
        else:
            y=i+(n-(i+q))
            a=a+sa[x:y]
    for i in a:
        if i =="a":
            count=count+1       
    return a



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()
