#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
def sockMerchant(n, ar):
    na=[]
    res=0
    counter=0
    for i in ar:
        if i not in na:
            na.append(i)
    for j in na:
        counter=0
        for k in ar:
            if j==k:
                counter=counter+1
        q=math.floor(counter/2)
        res=res+q

            
                
    return res


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
