#!/bin/python3

import math
import os
import random
import re
import sys
import math

# Complete the viralAdvertising function below.
def viralAdvertising(n):
    person=5
    liked=2
    newlike=2

    for i in range (2,n+1):
        shared=3*newlike
        newlike=math.floor(shared/2)
        liked=liked+newlike
    return liked




if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    result = viralAdvertising(n)

    fptr.write(str(result) + '\n')

    fptr.close()
